sudo: required

services:
    - docker

# Install docker-ce to support multi stage builds
before_install:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get -y install ucommon-utils docker-ce
    - sudo service mysql stop
    - alias md5="md5sum"

install:
    - ./console upd
    - ./console exec php-fpm composer install

script:
    - ./console tests

after_failure:
    - ./console logs

after_script:
    - ./console down
