version: '3'
services:
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
            MYSQL_DATABASE: ${DB_BASE}
        ports:
            - ${DB_PORT}:${DB_PORT}

    php-fpm:
        image: ${IMAGE_NAME}/symfony-app
        build:
            context: ./app
        volumes:
            - .bashrc:/root/.bashrc
        links:
            - mysql
        ports:
            - ${APP_PORT}:80
