version: '3'
services:
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - ${DB_PORT}:${DB_PORT}

    php-fpm:
        image: ${IMAGE_NAME}/laravel-app
        build:
            context: ./laravel
        volumes:
            - .bashrc:/root/.bashrc
            - ./laravel/app:/var/www/html/app
            - ./laravel/bootstrap:/var/www/html/bootstrap
            - ./laravel/config:/var/www/html/config
            - ./laravel/database:/var/www/html/database
            - ./laravel/public:/var/www/html/public
            - ./laravel/resources:/var/www/html/resources
            - ./laravel/routes:/var/www/html/routes
            - ./laravel/storage:/var/www/html/storage
            - ./laravel/tests:/var/www/html/tests
            - ./laravel/artisan:/var/www/html/artisan
            - ./laravel/composer.json:/var/www/html/composer.json
            - ./laravel/composer.lock:/var/www/html/composer.lock
            - ./laravel/package.json:/var/www/html/package.json
            - ./laravel/package-lock.json:/var/www/html/package-lock.json
            - ./laravel/phpunit.xml:/var/www/html/phpunit.xml
            - ./laravel/server.php:/var/www/html/server.php
            - ./laravel/webpack.mix.js:/var/www/html/webpack.mix.js
        links:
            - mysql
        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_CONNECTION: ${DB_CONNECTION}
            APP_NAME: ${APP_NAME}
            APP_ENV: ${APP_ENV}
            APP_KEY: ${APP_KEY}
            APP_DEBUG: ${APP_DEBUG}
            APP_URL: ${APP_URL}
            MOLLIE_KEY: ${MOLLIE_KEY}
        ports:
            - ${APP_PORT}:80
        entrypoint:
            './entrypoint-dev'
