version: '3'
services:
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - ${DB_PORT}:${DB_PORT}

    php-fpm:
        image: ${IMAGE_NAME}/laravel-app
        build:
            context: ./laravel
        volumes:
            - ./laravel:/var/www/html
            - .bashrc:/root/.bashrc
        links:
            - mysql
        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_CONNECTION: mysql
            APP_NAME: 'Partner Demo'
            APP_ENV: 'local'
            APP_KEY: 'base64:MhCRwfpgb9nkDUfTKxsv6VBF/L5SDPTG8udHDUde8d0='
            APP_DEBUG: 'true'
            APP_URL: 'http://localhost'
        ports:
            - ${APP_PORT}:80
        entrypoint:
            './entrypoint-dev'
