version: '3'
services:
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - ${DB_PORT}:${DB_PORT}
    php-fpm:
        links:
            - mysql
        entrypoint:
            './entrypoint-dev'
